id: test-corvette
name: HNS Viper
faction: Hostile
signature: 0.7
posture: Free

ai:
  behavior: Aggressive

classification:
  domain: Surface
  typeName: Viper-class missile corvette

sensor:
  rangeKm: 150
  maxDetectProbability: 0.9
  falloffExponent: 1.5

propulsion:
  maxSpeedKmPerTick: 0.4

health:
  max: 180

weapons:
  - projectilePrototype: AGM-89
    cooldownTicks: 20
    magazine: 6

  - pointDefense: true
    pointDefensePk: 0.4
    rangeKm: 8
    cooldownTicks: 1
    magazine: 150
