using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Lattice.Renderer.Xaml.Generator;

[Generator]
public sealed class NameReferenceGenerator : IIncrementalGenerator
{
    private const string ControlsNamespace = "global::Lattice.Renderer.Ui.Controls";
    private const string XamlNamespace = "global::Lattice.Renderer.Ui.Xaml";
    private const string MarkerAttribute = "Lattice.Renderer.Ui.Xaml.GenerateTypedNameReferencesAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<ImmutableArray<(string Name, string Text)>> xamlFiles =
            context.AdditionalTextsProvider
                .Where(static file => file.Path.EndsWith(".xaml", System.StringComparison.OrdinalIgnoreCase))
                .Select(static (file, ct) =>
                    (Name: Path.GetFileNameWithoutExtension(file.Path), Text: file.GetText(ct)?.ToString() ?? string.Empty))
                .Collect();

        IncrementalValueProvider<ImmutableArray<(string Namespace, string ClassName)>> classes =
            context.SyntaxProvider.ForAttributeWithMetadataName(
                MarkerAttribute,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    INamedTypeSymbol symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    string ns = symbol.ContainingNamespace.IsGlobalNamespace
                        ? string.Empty
                        : symbol.ContainingNamespace.ToDisplayString();
                    return (Namespace: ns, ClassName: symbol.Name);
                })
                .Collect();

        context.RegisterSourceOutput(classes.Combine(xamlFiles), static (spc, pair) =>
        {
            ImmutableArray<(string Namespace, string ClassName)> classList = pair.Left;
            ImmutableArray<(string Name, string Text)> xamlList = pair.Right;

            foreach ((string ns, string className) in classList)
            {
                (string Name, string Text) xaml = xamlList.FirstOrDefault(x => x.Name == className);
                if (xaml.Text is null || xaml.Text.Length == 0)
                {
                    continue;
                }

                List<(string Name, string Element)> names = ParseNamedElements(xaml.Text);
                spc.AddSource($"{className}.g.cs", SourceText.From(Emit(ns, className, names), Encoding.UTF8));
            }
        });
    }

    private static List<(string Name, string Element)> ParseNamedElements(string xaml)
    {
        List<(string, string)> result = new();
        XElement? root = XDocument.Parse(xaml).Root;
        if (root is null)
        {
            return result;
        }

        foreach (XElement element in root.Descendants())
        {
            XAttribute? name = element.Attributes().FirstOrDefault(a => a.Name.LocalName == "Name");
            if (name is not null)
            {
                result.Add((name.Value, element.Name.LocalName));
            }
        }

        return result;
    }

    private static string Emit(string ns, string className, List<(string Name, string Element)> names)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        if (ns.Length > 0)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial class ").Append(className)
          .Append(" : ").Append(XamlNamespace).AppendLine(".IXamlNameResolver");
        sb.AppendLine("{");

        foreach ((string name, string element) in names)
        {
            sb.Append("    private ").Append(ControlsNamespace).Append('.').Append(element)
              .Append(' ').Append(name).AppendLine(" = default!;");
        }

        sb.AppendLine();
        sb.Append("    void ").Append(XamlNamespace).Append(".IXamlNameResolver.Resolve(")
          .Append(XamlNamespace).AppendLine(".NameScope scope)");
        sb.AppendLine("    {");
        foreach ((string name, string element) in names)
        {
            sb.Append("        ").Append(name).Append(" = (").Append(ControlsNamespace).Append('.').Append(element)
              .Append(")scope.Lookup(\"").Append(name).AppendLine("\");");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
